config/routes.rb
RoutesProject::Application.routes.draw do

  get "routes/upload"
  post "routes/upload"
  post "routes/showAll"

  resources :routes do
    collection do
      get :destroy_all
    end
  end

  resources :general_route do
    collection do
      get :destroy_all
    end
  end

end

app/models/route.rb
class Route < ActiveRecord::Base
  has_many :gps_samples, :dependent => :destroy
  # Set attributes as accessible for mass-assignment
  attr_accessible :name, :description , :general_route_id

end

app/controllers/routes_controller.rb
require 'zip/zipfilesystem'
require 'json'

class RoutesController < ApplicationController

  def index
    @routes=Route.all
  end

  def show
    db = SQLite3::Database.open "db/development.sqlite3"
    db.results_as_hash = true

    @id = Route.find(params[:id])
    @general_route = GeneralRoute.find(@id.general_route_id)
    @gps = db.execute "SELECT routes.name, gps_samples.latitude, gps_samples.longitude, nfc_samples.timestamp,nfc_samples.message, surveys.answer
                      FROM  nfc_samples INNER JOIN surveys
                      ON nfc_samples.id = surveys.nfc_sample_id
                      INNER JOIN gps_samples
                      ON nfc_samples.gps_sample_id = gps_samples.id
                      INNER JOIN routes
                      ON gps_samples.route_id=routes.id
                      WHERE routes.id='"+params[:id]+"'
                      AND surveys.answer <>  '<null>' ORDER BY nfc_samples.timestamp"


    if @gps.length==0 #se eliminar las rutas vacias

      Route.delete(@id)
      redirect_to general_route_path(:id => @general_route.id), notice: 'The empty sensed was delete'
    end
    #Procesar los datos para mandar solamente una hash con el timestamp, el mensaje,  y un string donde se concatenen
    #los mensajes que se van a mostrar en la gps.

    ##########################################################
    #Procesar los datos para en el archivo que se manda, se concatenen los elementos con la misma gps para que el mensaje y el answer muestren cosas concatenadas.

    #TO DO: Si es repetida la NFC (message y timestamp) y el answer de la survey, no concatenar ni el mensaje, ni la respuesta. Ejm PARADA/PARADA

    count = 0
    @gps_array = []

    while !@gps[count + 1].nil? #
      if @gps[count]["latitude"] == @gps[count + 1]["latitude"] && @gps[count]["longitude"] == @gps[count + 1]["longitude"]
        source_hash = {"name" => @gps[count]["name"], "latitude" => @gps[count]["latitude"], "longitude" => @gps[count]["longitude"], "timestamp" => @gps[count]["timestamp"], "message" => @gps[count]["message"] + "/" + @gps[count + 1]["message"], "answer" => @gps[count]["answer"] + "/" + @gps[count + 1]["answer"]}
        @gps_array << source_hash
        count = count + 2
        #elsif @gps[count]["message"] == "FIN"
        #  source_hash = {"name" => @gps[count]["name"], "latitude" => @gps[count]["latitude"], "longitude" => @gps[count]["longitude"], "timestamp" => @gps[count]["timestamp"], "message" => @gps[count]["message"], "answer" => @gps[count]["answer"]}
        #  @gps_array << source_hash
      else
        source_hash = {"name" => @gps[count]["name"], "latitude" => @gps[count]["latitude"], "longitude" => @gps[count]["longitude"], "timestamp" => @gps[count]["timestamp"], "message" => @gps[count]["message"], "answer" => @gps[count]["answer"]}
        @gps_array << source_hash
        count = count + 1
      end
    end

    source_hash = {"name" => @gps[@gps.length - 1]["name"], "latitude" => @gps[@gps.length - 1]["latitude"], "longitude" => @gps[@gps.length - 1]["longitude"], "timestamp" => @gps[@gps.length - 1]["timestamp"], "message" => @gps[@gps.length - 1]["message"], "answer" => @gps[@gps.length - 1]["answer"]}
    @gps_array << source_hash

    count = 0
    @gps_array2 = []

    while !@gps_array[count + 1].nil? #
      if @gps_array[count]["latitude"] == @gps_array[count + 1]["latitude"] && @gps_array[count]["longitude"] == @gps_array[count + 1]["longitude"]
        source_hash = {"name" => @gps_array[count]["name"], "latitude" => @gps_array[count]["latitude"], "longitude" => @gps_array[count]["longitude"], "timestamp" => @gps_array[count]["timestamp"], "message" => @gps_array[count]["message"] + "/" + @gps_array[count + 1]["message"], "answer" => @gps_array[count]["answer"] + "/" + @gps_array[count + 1]["answer"]}
        @gps_array2 << source_hash
        count = count + 2
        #elsif @gps[count]["message"] == "FIN"
        #  source_hash = {"name" => @gps[count]["name"], "latitude" => @gps[count]["latitude"], "longitude" => @gps[count]["longitude"], "timestamp" => @gps[count]["timestamp"], "message" => @gps[count]["message"], "answer" => @gps[count]["answer"]}
        #  @gps_array << source_hash
      else
        source_hash = {"name" => @gps_array[count]["name"], "latitude" => @gps_array[count]["latitude"], "longitude" => @gps_array[count]["longitude"], "timestamp" => @gps_array[count]["timestamp"], "message" => @gps_array[count]["message"], "answer" => @gps_array[count]["answer"]}
        @gps_array2 << source_hash
        count = count + 1
      end
    end

    source_hash = {"name" => @gps_array[@gps_array.length - 1]["name"], "latitude" => @gps_array[@gps_array.length - 1]["latitude"], "longitude" => @gps_array[@gps_array.length - 1]["longitude"], "timestamp" => @gps_array[@gps_array.length - 1]["timestamp"], "message" => @gps_array[@gps_array.length - 1]["message"], "answer" => @gps_array[@gps_array.length - 1]["answer"]}
    @gps_array2 << source_hash

    ##########################################################
    ##### Se encuentran los datos de pasajeros por hora...

    @passengers = Passenger.find_all_by_route_id(@id)
    @array = []
    @array << @passengers.to_json


    ################################################################
    #Se busca la capacidad de pasajeros que puede llevar el camión
    @nfc_samples = NfcSample.all :joins => {:gps_sample => :route}, :conditions => {:gps_samples => {:route_id => @id}}
    @bus_size = 0

    @nfc_samples.each do |nfc|
      if nfc["message"]=="INICIO"

        @survey2 = Survey.find_all_by_nfc_sample_id(nfc)

        if !@survey2.nil?
          if !@survey2[0].nil?
            if !@survey2[0].answer.nil?
              @bus_size = @survey2[0].answer.to_i #Obtener la capacidad de pasajeros que puede llevar el camion de la ruta sensada
            end
          end
        end

      end
    end

    #######################################################

    #######################################################
    #Sacar la duración de la ruta en horas, minutos y segundos

    #Se buscan todos los NFC de ese sensado
    @nfc_samples = NfcSample.all :joins => {:gps_sample => :route}, :conditions => {:gps_samples => {:route_id => @id}}

    @nfc_samples.each do |nfc|
      if nfc["message"]=="INICIO"
        @time_start = nfc.timestamp #Se obtiene el timestamp del inicio
      end

      if nfc["message"]=="FIN"
        @time_end = nfc.timestamp #Se obtiene el ti  mestamp del final
      end
    end

    route_duration = @time_end.to_i - @time_start.to_i

    duration_seconds = route_duration/1000

    seconds = duration_seconds.to_i
    @duration = format_time (seconds) #Duración de la ruta actual en horas, minutos, segundos

    ################################################

    #################################################
    #Crear un arreglo de coordenadas GPS para enviarselas al mapa a partir del INICIO y FIN de los NFC, aunque no tengan NFC
    #Se buscan todas las coordenadas de ese sensado
    @gps_all = GpsSample.find_all_by_route_id(@id)

    #######################################################
  end

  def format_time (timeElapsed) #time in seconds

    @timeElapsed = timeElapsed

    #find the seconds
    seconds = @timeElapsed % 60

    #find the minutes
    minutes = (@timeElapsed / 60) % 60

    #find the hours
    hours = (@timeElapsed/3600)

    #format the time

    return hours.to_s + ":" + format("%02d", minutes.to_s) + ":" + format("%02d", seconds.to_s)
  end

  def showAll
    db = SQLite3::Database.open "db/development.sqlite3"
    db.results_as_hash = true


    if !params[:route].nil?

      @ids=params[:route]
      route = Route.find(@ids[0])
      @general_route = GeneralRoute.find(route.general_route_id)


      @gps=Array.new
      @color=Array.new
      @x=Array.new
      @duration=Array.new

      @ids.each do |id|
        #@gps.push (db.execute "SELECT routes.name, gps_samples.latitude, gps_samples.longitude, nfc_samples.timestamp,nfc_samples.message, surveys.answer
        #                FROM  nfc_samples INNER JOIN surveys
        #                ON nfc_samples.id = surveys.nfc_sample_id
        #                INNER JOIN gps_samples
        #                ON nfc_samples.gps_sample_id = gps_samples.id
        #                INNER JOIN routes
        #                ON gps_samples.route_id=routes.id
        #                WHERE routes.id='"+id+"'
        #                AND surveys.answer <>  '<null>'")

        @gps.push (GpsSample.find_all_by_route_id(id))

        @color.push("%06x" % (rand * 0xffffff))


        @x.push(Passenger.where("route_id=?", id).group("route_id,count").order("count(count) DESC").first)


        @nfc_samples = NfcSample.all :joins => {:gps_sample => :route}, :conditions => {:gps_samples => {:route_id => id}}

        @nfc_samples.each do |nfc|
          if nfc["message"]=="INICIO"
            @time_start = nfc.timestamp #Se obtiene el timestamp del inicio
          end

          if nfc["message"]=="FIN"
            @time_end = nfc.timestamp #Se obtiene el ti  mestamp del final
          end
        end

        route_duration = @time_end.to_i - @time_start.to_i

        duration_seconds = route_duration/1000

        seconds = duration_seconds.to_i
        @duration.push(format_time (seconds)) #Duración de la ruta actual en horas, minutos, segundos




      end

      @c=@color.clone
      @color = @color.to_s.gsub!("[", "")
      @color = @color.to_s.gsub!("]", "")

    else
      redirect_to :back, notice: 'Select a route'
    end

  end

  def destroy
    # find only the location that has the id defined in params[:id]
    @route = Route.find(params[:id])

    # delete the location object and any child objects associated with it
    @route.destroy

    # redirect the user to index
    general_route=GeneralRoute.find(@route.general_route_id)

app/views/routes/index.html.haml
= javascript_include_tag '/assets/maps/OpenLayers'
= javascript_include_tag '/assets/maps/locations'

%header
 %div#logo
 %h1.title All Routes



%table#table
 %thead
  %tr
   %th Routes
   %th
 %tbody
  - @routes.each do |route|
   %tr
    %td= link_to route.name, route_path(route.id)
    %td= route.description

%p=link_to "Upload Route", routes_upload_path

app/views/routes/show.html.haml
%header
 %div#logo
 %h1.title Show Route

= javascript_include_tag 'https://www.google.com/jsapi'
:javascript
  google.load('visualization', '1', {packages: ['corechart']});



%section#middle

 %h2="Route Name: " + @general_route.name
 %h3=@id.name
 %h4= "Route Duration: " + @duration
 %p= link_to 'Back to route: '+@general_route.name, general_route_path(@general_route)

 .map
  %div#map
  %input#gps{:type => "hidden", :value => @gps_array2.to_json}
  %input#gps_all{:type => "hidden", :value => @gps_all.to_json}

.container
 %div#container
 %input#passengers{:type => "hidden", :value => @passengers.to_json}

 %input#array{:type => "hidden", :value => @array}
 %input#bus_size{:type => "hidden", :value => @bus_size}

-#%p=@duration
-#
-#%p=@gps
-#
-#%p=@gps_array
-#
-#%p=@gps_array2

= javascript_include_tag '/assets/maps/OpenLayers'
= javascript_include_tag '/assets/maps/locations'
= javascript_include_tag '/assets/charts/charts'

:javascript
  initMap($("#gps").val(),$("#gps_all").val());
  drawVisualization($("#bus_size").val(),$("#container").val(),$("#array").val());

app/views/routes/showAll.html.haml
%header
 %div#logo
 %h1.title Show Routes

%section#middle
 %h2=@general_route.name

 %table#tableAll
  %thead
   %tr
    %th.a
    %th Name
    %th Max. Passengers
    %th Time
    %th Route Duration

   %tbody
   - @ids.each_with_index do |r, idx|
    -a="#"+@c[idx]
    %tr
     %td.a{:bgcolor => a }
     %td=Route.find(r).name
     %td=@x[idx].count
     %td=Time.at(@x[idx].timestamp.to_s[0..9].to_i).strftime("%H:%M:%S")
     %td=@duration[idx]



 %p= link_to 'Back to route: '+@general_route.name, general_route_path(@general_route)

 -#%p=@general_route.name
 -#%p=@id.name
 -#%p= link_to 'Back to route: '+@general_route.name, general_route_path(@general_route)

 .map
  %div#map
  %input#gps{:type => "hidden", :value => @gps.to_json}
  %input#color{:type => "hidden", :value => @color}


= javascript_include_tag '/assets/maps/OpenLayers'
= javascript_include_tag '/assets/maps/locations1'
= javascript_include_tag 'http://code.highcharts.com/stock/highstock.js'
= javascript_include_tag 'http://code.highcharts.com/stock/modules/exporting.js'
:javascript
  initMap($("#gps").val(),$("#color").val());

app/views/routes/upload.html.haml
%header
 %div#logo
 %h1.title Upload Sensed Route


%p= "Route: "+ @general_route.name

= form_tag routes_upload_path, :method => :post, :enctype=>"multipart/form-data" do
 = file_field_tag :file
 %input{:type => "hidden", :value=> @general_route.id, :name=>"id"}
 = submit_tag 'Upload'
 %p= show_flash


-if !@routes.nil?

 %table#table
  %thead
   %tr
    %th Name
    %th Date
   %tbody
   - @routes.each do |r|
    %tr
     %td=link_to r.name,  route_path(r.id)

%p= link_to 'Back to Routes list', general_route_index_path