config/routes.rb
RoutesProject::Application.routes.draw do

  get "routes/upload"
  post "routes/upload"
  post "routes/showAll"

  resources :routes do
    collection do
      get :destroy_all
    end
  end

  resources :general_route do
    collection do
      get :destroy_all
    end
  end

end

app/models/general_route.rb
class GeneralRoute< ActiveRecord::Base
  has_many :routes,:dependent => :destroy
  # attr_accessible :title, :body
  attr_accessible :name, :description
end

app/controllers/general_route_controller.rb
class GeneralRouteController < ApplicationController

  def index
    # get all locations in the table locations
    @general_routes = GeneralRoute.all

  end

  def new
    # default: render ’new’ template
  end

  def create
    # create a new instance variable called @location that holds a Location object built from the data the user submitted
    @general_route= GeneralRoute.new(params[:general_route])

    # if the object saves correctly to the database
    if @general_route.save
      # redirect the user to index
      redirect_to general_route_index_path
    else
      # redirect the user to the new method
      render action: 'new'
    end
  end

  def edit
    # find only the location that has the id defined in params[:id]
    @general_route = GeneralRoute.find(params[:id])
  end

  def update
    # find only the location that has the id defined in params[:id]
    @general_route = GeneralRoute.find(params[:id])

    # if the object saves correctly to the database
    if @general_route.update_attributes(params[:general_route])
      # redirect the user to index
      redirect_to general_route_index_path,  notice: 'Successful update'
    else
      # redirect the user to the edit method
      render action: 'edit'
    end
  end

  def destroy
    # find only the location that has the id defined in params[:id]
    @general_route = GeneralRoute.find(params[:id])

    # delete the location object and any child objects associated with it
    @general_route.destroy

    # redirect the user to index
    redirect_to general_route_index_path , notice: 'Delete'
  end

  def destroy_all
    # delete all location objects and any child objects associated with them
    GeneralRoute.destroy_all

    # redirect the user to index
    redirect_to general_route_index_path, notice: 'Delete All'
  end


  def show
    @general_route = GeneralRoute.find(params[:id])
    @routes=Route.find_all_by_general_route_id(params[:id])


  end


end

app/helpers/general_route_helper.rb
module GeneralRouteHelper
end

app/views/general_route/edit.html.haml
%header
  %div#logo
  %h1.title Update existing Route

= form_tag general_route_path(@general_route), :method => :put do

  = label :general_route, :name, 'Name'
  = text_field :general_route, :name

  = label :general_route, :description, 'Description'
  = text_area :general_route, :description

  %p
  = submit_tag 'Update Location Info'

%p
= link_to 'Back to location list', general_route_index_path

app/views/general_route/index.html.haml
%header
  %div#logo
  %h1.title All existing routes

%table#table
  %thead
    %tr
      %th Name
      %th Description
      %th
      %th
      %th

  %tbody
    - @general_routes.each do |route|
      %tr
        %td= link_to route.name, general_route_path(route)
        %td= route.description
        %td= link_to "Upload File", routes_upload_path(:id=> route.id)
        %td= link_to "Edit", edit_general_route_path(route)
        %td= link_to "Delete", general_route_path(route), :method => :delete, :confirm => 'Are you sure?'

%p= show_flash

%p=link_to "Create new Route", new_general_route_path

%p=link_to "Delete all", destroy_all_general_route_index_path, :method => :post, :confirm => 'Are you sure?'

app/views/general_route/new.html.haml
%header
  %div#logo
  %h1.title Create a new route

= form_tag general_route_index_path, :method => :post do

  = label :general_route, :name, 'Name'
  = text_field :general_route, :name

  = label :general_route, :description, 'Description'
  = text_area :general_route, :description

  %p
  = submit_tag 'Save Changes'

%p
= link_to 'Back to route list', general_route_index_path

app/views/general_route/show.html.haml
%header
 %div#logo
 %h1.title Show Sensed Routes

%p= "Name: " +@general_route.name
%p= "Description: " +@general_route.description
%p= show_flash

= form_tag routes_showAll_path, :method => :post do
 %table#table
  %thead
   %tr
    %th= check_box_tag  "allbox",nil, nil, {:onclick=>"checkAll();"}
    %th Name
    %th Date
    %th

  %tbody
   -@routes.each do |r|
    %tr
     %td=check_box_tag "route[]", r.id.to_s
     %td=link_to r.name,route_path(r.id)
     %td=Time.at(GpsSample.find_by_route_id(r.id).timestamp.to_s[0..9].to_i).strftime("%b - %d - %Y")
     %td=link_to "Delete", route_path(r.id), :method => :delete, :confirm => 'Are you sure?'

 %p= submit_tag 'View Selected Sensed'
%p= link_to 'Back to Routes list', general_route_index_path

:javascript
  function checkAll(){
  	for (var i=0;i<document.forms[0].elements.length;i++)
  	{
  		var e=document.forms[0].elements[i];
  		if ((e.name != 'allbox') && (e.type=='checkbox'))
  		{
  			e.checked=document.forms[0].allbox.checked;
  		}
  	}
  }